# Generated by Django 3.1.11 on 2021-05-18 23:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20210517_2325"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snekuser",
            name="registration_token",
        ),
        migrations.RemoveField(
            model_name="snekuser",
            name="telegram_user_id",
        ),
        migrations.RemoveField(
            model_name="snekuser",
            name="telegram_username",
        ),
        migrations.AlterField(
            model_name="snekuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 36 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=36,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
